### 查询课程信息
POST http://{{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 查询课程分类
GET {{gateway_host}}/content/course-category/tree-nodes


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 10,
  "originalPrice":100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "hgc",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "vjgh",
  "grade": "204001",
  "description": "java网络编程高级"
}

### 课程查询
GET {{content_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODM5ODg2MDQsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImM3OWRlZTQxLWEwMjItNDk1Ni05ZTg2LWRkYmEwMzZlM2FiNSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.4z3C7i9tXeUCsd9CxGjK-fahS0OF9Oku6NOnLEXGHGs



### 课程计划查询
GET {{content_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json


### 删除课程计划
DELETE {{content_host}}/content/teachplan/43


### 查询课程讲师
GET {{content_host}}/content/courseTeacher/list/80
#Content-Type: application/json

### 添加课程讲师
POST  {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "courseId": 75,
  "teacherName": "王老师",
  "position": "教师职位",
  "introduction": "教师简介"
}


### 修改课程讲师
PUT  {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 21,
  "courseId": 80,
  "teacherName": "王老师",
  "position": "教师职位",
  "introduction": "教师简介",
  "photograph": null,
  "createDate": null
}

### 删除课程
DELETE  {{content_host}}/content/course/87

### 通过网关访问资源服务
GET {{gateway_host}}/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NDA0MTk3MSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI5OGU2ZWNhMy00OWYyLTQxNGEtYmU4Mi0zMWVhOTc5MzBmZTUiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.0J3jxcUB5go4wxvy-FI6bDWa4s2F7iaKEdmc--6RbdQ